// <auto-generated />
namespace MovieMozo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SeedMembershipTypesWithName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedMembershipTypesWithName));
        
        string IMigrationMetadata.Id
        {
            get { return "201910191016312_SeedMembershipTypesWithName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
